site_name: Meritocracy
theme:
  name: 'material'


nav:
  - Home: 'index.md'
  - '导论':'Intro.md'
  - '综述': 'Outline.md'
  - '研究方法': 'Methods.md'
  - '研究发现': 'Discovery.md'
  - '行动建议': 'Solutions.md'


